---
apiVersion: v1
kind: Pod
metadata:
  name: disk-clean-cp-4
  namespace: rook-ceph
spec:
  restartPolicy: Never
  nodeName: cp-4
  volumes:
    - name: rook-data-dir
      hostPath:
        path: /var/lib/rook
  containers:
    - name: disk-clean
      image: busybox@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
      securityContext:
        privileged: true
      volumeMounts:
        - name: rook-data-dir
          mountPath: /node/rook-data
      command:
        - /bin/sh
        - -c
        - rm -rf /node/rook-data/*

---
apiVersion: v1
kind: Pod
metadata:
  name: disk-clean-cp-1
  namespace: rook-ceph
spec:
  restartPolicy: Never
  nodeName: cp-1
  volumes:
    - name: rook-data-dir
      hostPath:
        path: /var/lib/rook
  containers:
    - name: disk-clean
      image: busybox@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
      securityContext:
        privileged: true
      volumeMounts:
        - name: rook-data-dir
          mountPath: /node/rook-data
      command:
        - /bin/sh
        - -c
        - rm -rf /node/rook-data/*

---
apiVersion: v1
kind: Pod
metadata:
  name: disk-clean-cp-2
  namespace: rook-ceph
spec:
  restartPolicy: Never
  nodeName: cp-2
  volumes:
    - name: rook-data-dir
      hostPath:
        path: /var/lib/rook
  containers:
    - name: disk-clean
      image: busybox@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
      securityContext:
        privileged: true
      volumeMounts:
        - name: rook-data-dir
          mountPath: /node/rook-data
      command:
        - /bin/sh
        - -c
        - rm -rf /node/rook-data/*

---
apiVersion: v1
kind: Pod
metadata:
  name: disk-clean-cp-3
  namespace: rook-ceph
spec:
  restartPolicy: Never
  nodeName: cp-3
  volumes:
    - name: rook-data-dir
      hostPath:
        path: /var/lib/rook
  containers:
    - name: disk-clean
      image: busybox@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
      securityContext:
        privileged: true
      volumeMounts:
        - name: rook-data-dir
          mountPath: /node/rook-data
      command:
        - /bin/sh
        - -c
        - rm -rf /node/rook-data/*
