---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname kubestash
  namespace: flux-system
spec:
  targetNamespace: kubestash
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./k8s/apps/kubestash/kubestash/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  dependsOn:
    - name: cluster-apps-rook-ceph-cluster
