---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openweb-ui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: openweb-ui-secret
    template:
      data:
        OPENAI_API_KEY: "{{ .litellm_master_key }}"
        REDIS_URL: |-
          redis://openweb-ui-dragonfly:6379/0
        WEBSOCKET_REDIS_URL: |-
          redis://openweb-ui-dragonfly:6379/0
#        DATABASE_URL: |-
#          postgres://{{ .OPENWEBUI_POSTGRES_USER }}:{{ .OPENWEBUI_POSTGRES_PASSWORD }}@postgres-pgbouncer-rw.database.svc.cluster.local/{{ .OPENWEBUI_POSTGRES_DB }}
  dataFrom:
    - extract:
        key: litellm
      rewrite:
        - regexp:
            source: "(.*)"
            target: "litellm_$1"

---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openweb-ui-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: openweb-ui-db-secret
    template:
      type: Opaque
      data:
        AUTOBRR__DATABASE_TYPE: postgres
        AUTOBRR__POSTGRES_HOST: '{{ index . "pgbouncer-host" }}'
        AUTOBRR__POSTGRES_PORT: '{{ index . "pgbouncer-port" }}'
        AUTOBRR__POSTGRES_DATABASE: '{{ index . "dbname" }}'
        AUTOBRR__POSTGRES_USER: '{{ index . "user" }}'
        AUTOBRR__POSTGRES_PASS: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-
