---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openweb-ui
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: openweb-ui-secret
    template:
      data:
        OPENAI_API_KEY: "{{ .litellm_master_key }}"
        REDIS_URL: |-
          redis://openweb-ui-dragonfly:6379/0
        WEBSOCKET_REDIS_URL: |-
          redis://openweb-ui-dragonfly:6379/0
#        DATABASE_URL: |-
#          postgres://{{ .OPENWEBUI_POSTGRES_USER }}:{{ .OPENWEBUI_POSTGRES_PASSWORD }}@postgres-pgbouncer-rw.database.svc.cluster.local/{{ .OPENWEBUI_POSTGRES_DB }}
  dataFrom:
    - extract:
        key: litellm
      rewrite:
        - regexp:
            source: "(.*)"
            target: "litellm_$1"
