---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/toolhive.stacklok.dev/embeddingserver_v1beta1.json
apiVersion: toolhive.stacklok.dev/v1beta1
kind: EmbeddingServer
metadata:
  name: mcp-tools-embedding
spec:
  model: sentence-transformers/all-MiniLM-L6-v2
  image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest@sha256:e04661a70f78b4be988e1bb901e5256d1201381811db1f27c14805e6a848cd50
  env:
    - name: HOSTNAME
      value: "::"
