---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: frigate
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: frigate
    creationPolicy: Owner
    template:
      data:
        "FRIGATE_MQTT_USERNAME": "{{ .frigate_username }}"
        "FRIGATE_MQTT_PASSWORD": "{{ .frigate_password }}"
        "FRIGATE_RTSP_USER": "{{ .go2rtc_username }}"
        "FRIGATE_RTSP_PASSWORD": "{{ .go2rtc_password }}"
  dataFrom:
    - extract:
        key: frigate
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9-]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "frigate_$1"
    - extract:
        key: go2rtc
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9-]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "go2rtc_$1"
