---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: homepage-secret
    creationPolicy: Owner
  data:
    - secretKey: HOMEPAGE_VAR_QNAP_USER
      remoteRef:
        key: qnap
        property: username
    - secretKey: HOMEPAGE_VAR_QNAP_PASS
      remoteRef:
        key: qnap
        property: password
