---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mikrotik-mcp
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mikrotik-mcp-secret
    creationPolicy: Owner
    template:
      data:
        MIKROTIK_HOST: "{{ .mikrotik_mcp_host }}"
        MIKROTIK_USERNAME: "{{ .mikrotik_mcp_username }}"
        MIKROTIK_PASSWORD: "{{ .mikrotik_mcp_password }}"
  dataFrom:
    - extract:
        key: mikrotik-mcp
      rewrite:
        - regexp:
            source: "[^a-zA-Z0-9-]"
            target: "_"
        - regexp:
            source: "(.*)"
            target: "mikrotik_mcp_$1"
