---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: litellm
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: litellm-secret
    template:
      data:
        LITELLM_MASTER_KEY: "{{ .litellm_master_key }}"
        OPENCODE_GO_API_KEY: "{{ .litellm_opencode_api_key }}"
        GEMINI_API_KEY: "{{ .litellm_gemini_api_key }}"
  dataFrom:
    - extract:
        key: litellm
      rewrite:
        - regexp:
            source: "(.*)"
            target: "litellm_$1"
