---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lingarr
spec:
  refreshInterval: 5m
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lingarr-secret
    creationPolicy: Owner
  data:
    - secretKey: RADARR_API_KEY
      remoteRef:
        key: radarr
        property: api_key
    - secretKey: SONARR_API_KEY
      remoteRef:
        key: sonarr
        property: api_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lingarr-db
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: crunchy-pgo-secrets
    kind: ClusterSecretStore
  target:
    name: lingarr-db-secret
    template:
      type: Opaque
      data:
        DB_CONNECTION: postgresql
        DB_HOST: '{{ index . "host" }}'
        DB_PORT: '{{ index . "port" }}'
        DB_DATABASE: '{{ index . "dbname" }}'
        DB_USERNAME: '{{ index . "user" }}'
        DB_PASSWORD: '{{ index . "password" }}'
  dataFrom:
    - extract:
        key: postgres-pguser-lingarr
