---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lingarr
spec:
  chartRef:
    kind: OCIRepository
    name: lingarr
  interval: 30m
  values:
    controllers:
      lingarr:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 2000
            fsGroupChangePolicy: "OnRootMismatch"
            runAsGroup: 2000
            runAsNonRoot: true
            runAsUser: 2000
            supplementalGroups:
              - 568
              - 100
        containers:
          app:
            image:
              repository: ghcr.io/lingarr-translate/lingarr
              tag: 1.3.0@sha256:12473f6f40beac1bb91ffadc7d8c7f1c2a0cd99ba336e4bf2c1dfa617c27a763
            env:
              TZ: Europe/Warsaw
              ASPNETCORE_URLS: http://+:9876
              AUTH_ENABLED: "false"
              TELEMETRY_ENABLED: "false"
              RADARR_URL: http://radarr.downloads.svc.cluster.local:7878
              SONARR_URL: http://sonarr.downloads.svc.cluster.local:8989
            envFrom:
              - secretRef:
                  name: lingarr-secret
              - secretRef:
                  name: lingarr-db-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 9876
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  failureThreshold: 30
                  periodSeconds: 10
            resources:
              requests:
                cpu: 20m
                memory: 256Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

    service:
      app:
        controller: lingarr
        ports:
          http:
            port: *port

    route:
      app:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Subtitle translation
          gethomepage.dev/group: Downloads
          gethomepage.dev/icon: sh-lingarr.png
          gethomepage.dev/name: Lingarr
          gethomepage.dev/app: lingarr
        hostnames: ["{{ .Release.Name }}.k8sj.io"]
        parentRefs:
          - name: envoy-internal
            namespace: networking

    persistence:
      config:
        existingClaim: lingarr
        globalMounts:
          - path: /app/config
      media:
        type: nfs
        server: nfs.dom.lan
        path: /volume1/Downloads
        globalMounts:
          - path: /storage/downloads
      qnap:
        type: nfs
        server: qnap.dom.lan
        path: /Share
        globalMounts:
          - path: /storage/qnap
      tmpfs:
        type: emptyDir
        globalMounts:
          - path: /tmp
